# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/hassio-addons/base:17.2.4
  amd64: ghcr.io/hassio-addons/base:17.2.4
  armhf: ghcr.io/hassio-addons/base:17.2.4
  armv7: ghcr.io/hassio-addons/base:17.2.4
  i386: ghcr.io/hassio-addons/base:17.2.4

labels:
  org.opencontainers.image.title: "Home Assistant Add-on: CarConnectivity Edge"
  org.opencontainers.image.description: "Addon version of Carconnectivity Edge made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
  org.opencontainers.image.source: "https://github.com/Pulpyyyy/carconnectivity-addon"
  org.opencontainers.image.licenses: "Apache License 2.0"

args:
  NGINX_VERSION: "1.26.3"
  SEAT_VERSION: "v0.3"
  SKODA_VERSION: "v0.6"
  VW_VERSION: "v0.6"
  TRONITY_VERSION: "v0.5"
  VOLVO_VERSION: "v0.1a1"
  MQTT_VERSION: "v0.6"
  MQTTHA_VERSION: "v0.3"
  WEBUI_VERSION: "v0.4"
  CC_VERSION: "v0.6.1a2"
