name: "CarConnectivity Addon"
version: "1.0.0"
slug: "carconnectivity-addon"
description: "Addon version of Carconnectivity made by Till (see https://github.com/tillsteinbach/CarConnectivity) throught MQTT"
panel_icon: "mdi:robot-mower-outline"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ingress: true
init: false
options:
  log_level: "debug"
  connector_type: "seatcupra"
  connector_log_level: "debug"
  connector_username: "mail@mail.com"
  connector_password: "password1"
  connector_spin: "1234"
  webui_log_level: "error"
  webui_username: "admin"
  webui_password: "secret"
  mqtt_log_level: "error"
  mqtt_username: "mqtt"
  mqtt_password: "password1"
  mqtt_broker: "192.168.1.52"
  mqtt_ha_log_level: "debug"
schema:
  log_level:
    type: "select"
    options:
      - "debug"
      - "info"
      - "warning"
      - "error"
  connector_type: "str"
  connector_log_level: "str"
  username: "str"
  password: "str"
  spin: "str"
  webui_log_level: "str"
  webui_username: "str"
  webui_password: "str"
  mqtt_log_level: "str"
  mqtt_username: "str"
  mqtt_password: "str"
  mqtt_broker: "str"
  mqtt_ha_log_level: "str"