name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Read configurations from build.yaml
        run: |
          echo "ARCHS=$(yq eval -o=json '.build.arch' build.yaml)" >> $GITHUB_ENV
          echo "BUILD_ARGS=$(yq eval -o=json '.build.args' build.yaml | jq -r 'to_entries | map("--build-arg " + .key + "=" + .value) | join(" ")')" >> $GITHUB_ENV
          echo "BASE_IMAGES=$(yq eval -o=json '.build.build_from' build.yaml | jq -c '.')" >> $GITHUB_ENV
          echo "VERSION=$(yq eval '.version' config.yaml)" >> $GITHUB_ENV

      - name: Build and push Docker images
        run: |
          DOCKER_REPO="${{ secrets.DOCKERHUB_USERNAME }}/carconnectivity-addon"
          ARCHS=$(echo "${{ env.ARCHS }}" | jq -r '.[]')
          BUILD_ARGS="${{ env.BUILD_ARGS }}"
          BASE_IMAGES=$(echo '${{ env.BUILD_FROM }}' | jq -r 'to_entries[] | "\(.key):\(.value)"')

          for ARCH in $ARCHS; do
            BASE_IMAGE=$(echo "$BUILD_ARGS" | grep "^$ARCH:" | cut -d':' -f2)
            
            echo "Building for architecture: $ARCH with base image $BASE_IMAGE"

            docker buildx build \
              --platform linux/$ARCH \
              --build-arg BUILD_FROM=$BASE_IMAGE \
              $BUILD_ARGS \
              --tag $DOCKER_REPO:$VERSION-$ARCH \
              --tag $DOCKER_REPO:latest-$ARCH \
              --push .
          done
