name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Install yq (for YAML to JSON conversion)
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Convert YAML to JSON
        run: |
          yq eval config.yaml --tojson > config.json

      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --all \
            --target / \
            --docker-hub pulpyyyy/carconnectivity-addon
