name: Build and Push Docker Images
permissions:
  contents: read
  packages: write
  id-token: write

on:
  workflow_run:
    workflows: ["Update build.yaml on new submodule release"]
    types:
      - completed
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  REPOSITORY: pulpyyyy
  REGISTRY: docker.io

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_addon:
    name: Build addon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, armhf, armv7, aarch64, i386]
        addon: [carconnectivity-addon, carconnectivity-addon-edge]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./"

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Check if Docker image exists
        run: |
          IMAGE="${{ env.REPOSITORY }}/${{ matrix.addon }}-${{ matrix.arch }}"
          VERSION=$(grep -E '^version:' "${{ matrix.addon }}/config.yaml" | awk '{print $2}' | sed 's/"//g')
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" "https://hub.docker.com/v2/repositories/$IMAGE/tags/$VERSION")
          echo "VERSION=$" >> $GITHUB_ENV
          if [ "$STATUS" -eq 404 ]; then
            echo "IMAGE_EXISTS=false" >> $GITHUB_ENV
            echo "The image $IMAGE:$VERSION does not exist on Docker Hub."
          else
            echo "IMAGE_EXISTS=true" >> $GITHUB_ENV
            echo "The image $IMAGE:$VERSION exists on Docker Hub."
          fi

      - name: Publish ${{ matrix.arch }} builder
        if: env.IMAGE_EXISTS == 'false'
        uses: home-assistant/builder@2025.03.0
        with:
          args: |
            --addon \
            --${{ matrix.arch }} \
            --docker-hub "${{ env.REGISTRY }}" \
            --target /data/${{ matrix.addon }} \
            --image "${{ env.REPOSITORY }}/${{ matrix.addon }}-${{ matrix.arch }}"

  publish_manifest:
    name: Publish Multi-Arch Manifest
    runs-on: ubuntu-latest
    needs: build_addon
    strategy:
      matrix:
        addon: [carconnectivity-addon, carconnectivity-addon-edge]

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and Push Multi-Arch Manifest for ${{ matrix.addon }}
        run: |
          IMAGES=""
          for ARCH in ${{ matrix.arch }}; do
            IMAGES="$IMAGES ${{ env.REPOSITORY }}/${{ matrix.addon }}-$ARCH"
          done

          docker manifest create "${{ env.REPOSITORY }}/${{ matrix.addon }}:latest" "$IMAGES"
          docker manifest push "${{ env.REPOSITORY }}/${{ matrix.addon }}:latest"
          docker manifest create "${{ env.REPOSITORY }}/${{ matrix.addon }}:${{ env.VERSION }}" "$IMAGES"
          docker manifest push "${{ env.REPOSITORY }}/${{ matrix.addon }}:${{ env.VERSION }}"
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
