name: Build and Push Docker Images

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
env:
  REPOSITORY: pulpyyyy
  REGISTRY: docker.io
  GIT_TAG_NAME: dev
  
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_addon:
    name: Build addon
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, armhf, armv7, aarch64,  i386]
        addon: [carconnectivity-addon, carconnectivity-addon-edge]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2

      - name: Get information
        id: info
        uses: home-assistant/actions/helpers/info@master
        with:
          path: "./"
        
      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Publish ${{ matrix.architecture }} builder
        uses: home-assistant/builder@2025.02.0
        with:
          args: |
            --addon \
            --${{ matrix.arch }} \
            --docker-hub "${{ env.REGISTRY }}" \
            --target /data/${{ matrix.addon }} \
            --image "${{ env.REPOSITORY }}/${{ matrix.addon }}-${{ matrix.arch }}"
