name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
env:
  REGISTRY: pulpyyyy/carconnectivity-addon

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_rtl_433:
    name: Build rtl_433 addon
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch: [armhf, armv7, aarch64, amd64, i386]
        addon: [carconnectivity-addon]

    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v4

    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to Packages Container registry
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build ${{ matrix.addon }} ${{ matrix.arch }} image
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ github.repository}}-${{ matrix.addon }}-{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target ${{ matrix.addon }}

    - name: Build and push ${{ matrix.addon }} ${{ matrix.arch }} image
      uses: home-assistant/builder@master
      if: github.event.pull_request.head.repo.full_name == github.repository
      with:
        args: |
          --${{ matrix.arch }} \
          --docker-hub $REGISTRY \
          --image ${{ env.REGISTRY }}-${{ matrix.addon }}-{arch} \
          --self-cache \
          --version $GITHUB_REF_SLUG \
          --no-latest \
          --target ${{ matrix.addon }}
