name: Translate Readme
permissions:
  contents: write
  pull-requests: write
  
on:
    push:
      paths:
        - README
      workflow_dispatch: # Allows manually triggering the action if needed

jobs:
    translate:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 3

            - name: Auto Translate
              uses: Lin-jun-xiang/action-translate-readme@v2 # Based on the tag
              with:
                token: ${{ secrets.ACTION_BOT }} # Based on step2 name
                # zhipuai: ${{ secrets.zhipuai_api_key }} # Optional: Based on step3
                # openai: ${{ secrets.OPENAI_API_KEY }}  # Optional: Based on step3
                langs: "English,French,Italian,German,Spanish,Polish,Portuguese" # You can define any langs

            - name: Copy README to README.md
              run: cp README README.md
      
            - name: Commit and push changes
              run: |
                git config --global user.name "github-actions[bot]"
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git add README.md
                git rm README.English.md
                git commit -m "Automated: Copy README to README.md" || echo "No changes to commit"
                git push
